export enum ContractGroup {
  APESWAP = 'APESWAP',
  CHAINLINK_FEED = 'CHAINLINK_FEED',
  GELATO = 'GELATO',
  TOKEN = 'TOKEN',
  EONIAN_VAULT = 'EONIAN_VAULT',
  EONIAN_HEALTH_CHECK = 'EONIAN_HEALTH_CHECK',
  EONIAN_TREASURY = 'EONIAN_TREASURY',
}
