files:
  - output: eonian-sepolia-testnet.yaml
    data:
      network: sepolia
      description: The subgraph of Eonian yield aggregator protocol for Sepolia testnet
      vault:
        address: "0x9CF03106c5542932113574efCD38BaE5F3de204a"
        startBlock: 3726610

  - output: eonian-bsc-development.yaml
    data:
      network: bsc
      description: The subgraph of Eonian yield aggregator protocol for Binance Smart Chain development environment
      vault:
        address: "0xe782b7277725ccc8b9BDeE0fad8B4D87503d9436"
        startBlock: 29538460
