files:
  - output: eonian-sepolia-testnet.yaml
    data:
      network: sepolia
      description: The subgraph of Eonian yield aggregator protocol for Sepolia testnet
      schema: ../../schema.graphql
      vaults:
        - name: "USDT Vault"
          address: "0x9CF03106c5542932113574efCD38BaE5F3de204a"
          startBlock: 3726610
        - name: "USDC Vault"
          address: "0xaEAc5252d56a57fE5F3208B4B56a9B99d05047aF" 
          startBlock: 3950873
        - name: "BUSD Vault"
          address: "0xF4017645775b592Abe0801420eADd17E3585184c"
          startBlock: 3950878
      abis:
        Vault: ../../abis/VaultImplementation.json
        ERC20: ../../abis/ERC20.json
        ChainLinkPriceFeed: ../../abis/ChainLinkPriceFeed.json
      eventHandlers:
        file: ../../src/event-handlers.ts

  - output: eonian-bsc-development.yaml
    data:
      network: bsc
      description: The subgraph of Eonian yield aggregator protocol for Binance Smart Chain development environment
      schema: ../../schema.graphql
      vaults:
        - name: "USDT Vault"
          address: "0x1D0cC9fa6AcBdD11a9BF1153628A634313496878" 
          startBlock: 29618633
        - name: "USDC Vault"
          address: "0x8450D8f56E68630b37f18B51A09bcFEab5C60A89" 
          startBlock: 30281419
        - name: "BUSD Vault"
          address: "0x914b5763cFc6DaA9b7A968AdFf0Cbb0d817326B4"
          startBlock: 30281432
      abis:
        Vault: ../../abis/VaultImplementation.json
        ERC20: ../../abis/ERC20.json
        ChainLinkPriceFeed: ../../abis/ChainLinkPriceFeed.json
      eventHandlers:
        file: ../../src/event-handlers.ts

  - output: eonian-bsc-staging.yaml
    data:
      network: bsc
      description: The subgraph of Eonian yield aggregator protocol for Binance Smart Chain staging environment
      schema: ../../schema.graphql
      vaults:
        - name: "USDT Vault"
          address: "0x2c5BC0e128a3543bfb6F05eEA78506Fa5F952bE2"
          startBlock: 29619484
      abis:
        Vault: ../../abis/VaultImplementation.json
        ERC20: ../../abis/ERC20.json
        ChainLinkPriceFeed: ../../abis/ChainLinkPriceFeed.json
      eventHandlers:
        file: ../../src/event-handlers.ts

  # used primarly for testing
  # matchstick framework doesn't allow to pass the path to the schema
  - output: local.yaml 
    data:
      network: sepolia
      description: The subgraph of Eonian yield aggregator protocol for Sepolia testnet
      schema: ./schema.graphql
      vaults:
        - name: "USDT Vault"
          address: "0x9CF03106c5542932113574efCD38BaE5F3de204a"
          startBlock: 3726610
      abis:
        Vault: ./abis/VaultImplementation.json
        ERC20: ./abis/ERC20.json
        ChainLinkPriceFeed: ./abis/ChainLinkPriceFeed.json
      eventHandlers:
        file: ./src/event-handlers.ts