files:
  - output: eonian-sepolia-testnet.yaml
    data:
      network: sepolia
      description: The subgraph of Eonian yield aggregator protocol for Sepolia testnet
      schema: ../../schema.graphql
      vaults:
        - address: "0x9CF03106c5542932113574efCD38BaE5F3de204a" # USDT
          startBlock: 3726610
        - address: "0xaEAc5252d56a57fE5F3208B4B56a9B99d05047aF" # USDC
          startBlock: 3950873
        - address: "0xF4017645775b592Abe0801420eADd17E3585184c" # BUSD
          startBlock: 3950878
      abis:
        Vault: ../../abis/VaultImplementation.json
        ERC20: ../../abis/ERC20.json
        ChainLinkPriceFeed: ../../abis/ChainLinkPriceFeed.json
      eventHandlers:
        file: ../../src/event-handlers.ts

  - output: eonian-bsc-development.yaml
    data:
      network: bsc
      description: The subgraph of Eonian yield aggregator protocol for Binance Smart Chain development environment
      schema: ../../schema.graphql
      vaults:
        - address: "0x1D0cC9fa6AcBdD11a9BF1153628A634313496878" # USDT
          startBlock: 29618633
      abis:
        Vault: ../../abis/VaultImplementation.json
        ERC20: ../../abis/ERC20.json
        ChainLinkPriceFeed: ../../abis/ChainLinkPriceFeed.json
      eventHandlers:
        file: ../../src/event-handlers.ts

  - output: eonian-bsc-staging.yaml
    data:
      network: bsc
      description: The subgraph of Eonian yield aggregator protocol for Binance Smart Chain staging environment
      schema: ../../schema.graphql
      vaults:
        - address: "0x2c5BC0e128a3543bfb6F05eEA78506Fa5F952bE2" # USDT
          startBlock: 29619484
      abis:
        Vault: ../../abis/VaultImplementation.json
        ERC20: ../../abis/ERC20.json
        ChainLinkPriceFeed: ../../abis/ChainLinkPriceFeed.json
      eventHandlers:
        file: ../../src/event-handlers.ts

  # used primarly for testing
  # matchstic framework not aloow to pass path to the schema
  - output: local.yaml 
    data:
      network: sepolia
      description: The subgraph of Eonian yield aggregator protocol for Sepolia testnet
      schema: ./schema.graphql
      vaults:
        - address: "0x9CF03106c5542932113574efCD38BaE5F3de204a" # USDT
          startBlock: 3726610
      abis:
        Vault: ./abis/VaultImplementation.json
        ERC20: ./abis/ERC20.json
        ChainLinkPriceFeed: ./abis/ChainLinkPriceFeed.json
      eventHandlers:
        file: ./src/event-handlers.ts