specVersion: 1.0.0
description: The subgraph of Eonian yield aggregator protocol for Sepolia testnet
repository: https://github.com/eonian-core/farm
indexerHints:
  prune: auto
schema:
  file: ../../schema.graphql
dataSources:
  - kind: ethereum
    name: USDT Vault
    network: sepolia
    source:
      address: "0x9CF03106c5542932113574efCD38BaE5F3de204a"
      abi: Vault
      startBlock: 3726610
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Vault
        - ContractAdminChanged
        - Approval
        - AuthorizedOperator
        - ContractBeaconUpgraded
        - BorrowerDebtManagementReported
        - Burned
        - Deposit
        - Initialized
        - LockedProfitReleaseRateChanged
        - Minted
        - OwnershipTransferred
        - Paused
        - RevokedOperator
        - Sent
        - StrategyAdded
        - StrategyRemoved
        - StrategyReturnedToQueue
        - StrategyRevoked
        - Transfer
        - Unpaused
        - ContractUpgraded
        - Withdraw
      abis:
        - name: Vault
          file: ../../abis/VaultImplementation.json
        - name: ERC20
          file: ../../abis/ERC20.json
        - name: ChainLinkPriceFeed
          file: ../../abis/ChainLinkPriceFeed.json
      eventHandlers:
        - event: AdminChanged(address,address)
          handler: handleAdminChanged
        - event: Approval(indexed address,indexed address,uint256)
          handler: handleApproval
        - event: AuthorizedOperator(indexed address,indexed address)
          handler: handleAuthorizedOperator
        - event: BeaconUpgraded(indexed address)
          handler: handleBeaconUpgraded
        - event: BorrowerDebtManagementReported(indexed
            address,uint256,uint256,uint256,uint256,uint256)
          handler: handleBorrowerDebtManagementReported
        - event: Burned(indexed address,indexed address,uint256,bytes,bytes)
          handler: handleBurned
        - event: Deposit(indexed address,indexed address,uint256,uint256)
          handler: handleDeposit
        - event: Initialized(uint8)
          handler: handleInitialized
        - event: LockedProfitReleaseRateChanged(uint256)
          handler: handleLockedProfitReleaseRateChanged
        - event: Minted(indexed address,indexed address,uint256,bytes,bytes)
          handler: handleMinted
        - event: OwnershipTransferred(indexed address,indexed address)
          handler: handleOwnershipTransferred
        - event: Paused(address)
          handler: handlePaused
        - event: RevokedOperator(indexed address,indexed address)
          handler: handleRevokedOperator
        - event: Sent(indexed address,indexed address,indexed address,uint256,bytes,bytes)
          handler: handleSent
        - event: StrategyAdded(indexed address,uint256)
          handler: handleStrategyAdded
        - event: StrategyRemoved(indexed address,bool)
          handler: handleStrategyRemoved
        - event: StrategyReturnedToQueue(indexed address)
          handler: handleStrategyReturnedToQueue
        - event: StrategyRevoked(indexed address)
          handler: handleStrategyRevoked
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Unpaused(address)
          handler: handleUnpaused
        - event: Upgraded(indexed address)
          handler: handleUpgraded
        - event: Withdraw(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleWithdraw
      file: ../../src/event-handlers.ts
  - kind: ethereum
    name: USDC Vault
    network: sepolia
    source:
      address: "0xaEAc5252d56a57fE5F3208B4B56a9B99d05047aF"
      abi: Vault
      startBlock: 3950873
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Vault
        - ContractAdminChanged
        - Approval
        - AuthorizedOperator
        - ContractBeaconUpgraded
        - BorrowerDebtManagementReported
        - Burned
        - Deposit
        - Initialized
        - LockedProfitReleaseRateChanged
        - Minted
        - OwnershipTransferred
        - Paused
        - RevokedOperator
        - Sent
        - StrategyAdded
        - StrategyRemoved
        - StrategyReturnedToQueue
        - StrategyRevoked
        - Transfer
        - Unpaused
        - ContractUpgraded
        - Withdraw
      abis:
        - name: Vault
          file: ../../abis/VaultImplementation.json
        - name: ERC20
          file: ../../abis/ERC20.json
        - name: ChainLinkPriceFeed
          file: ../../abis/ChainLinkPriceFeed.json
      eventHandlers:
        - event: AdminChanged(address,address)
          handler: handleAdminChanged
        - event: Approval(indexed address,indexed address,uint256)
          handler: handleApproval
        - event: AuthorizedOperator(indexed address,indexed address)
          handler: handleAuthorizedOperator
        - event: BeaconUpgraded(indexed address)
          handler: handleBeaconUpgraded
        - event: BorrowerDebtManagementReported(indexed
            address,uint256,uint256,uint256,uint256,uint256)
          handler: handleBorrowerDebtManagementReported
        - event: Burned(indexed address,indexed address,uint256,bytes,bytes)
          handler: handleBurned
        - event: Deposit(indexed address,indexed address,uint256,uint256)
          handler: handleDeposit
        - event: Initialized(uint8)
          handler: handleInitialized
        - event: LockedProfitReleaseRateChanged(uint256)
          handler: handleLockedProfitReleaseRateChanged
        - event: Minted(indexed address,indexed address,uint256,bytes,bytes)
          handler: handleMinted
        - event: OwnershipTransferred(indexed address,indexed address)
          handler: handleOwnershipTransferred
        - event: Paused(address)
          handler: handlePaused
        - event: RevokedOperator(indexed address,indexed address)
          handler: handleRevokedOperator
        - event: Sent(indexed address,indexed address,indexed address,uint256,bytes,bytes)
          handler: handleSent
        - event: StrategyAdded(indexed address,uint256)
          handler: handleStrategyAdded
        - event: StrategyRemoved(indexed address,bool)
          handler: handleStrategyRemoved
        - event: StrategyReturnedToQueue(indexed address)
          handler: handleStrategyReturnedToQueue
        - event: StrategyRevoked(indexed address)
          handler: handleStrategyRevoked
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Unpaused(address)
          handler: handleUnpaused
        - event: Upgraded(indexed address)
          handler: handleUpgraded
        - event: Withdraw(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleWithdraw
      file: ../../src/event-handlers.ts
  - kind: ethereum
    name: WETH Vault
    network: sepolia
    source:
      address: "0x95E1DaFe365ddeF1C16981FBe376Af5610f87af6"
      abi: Vault
      startBlock: 4808163
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Vault
        - ContractAdminChanged
        - Approval
        - AuthorizedOperator
        - ContractBeaconUpgraded
        - BorrowerDebtManagementReported
        - Burned
        - Deposit
        - Initialized
        - LockedProfitReleaseRateChanged
        - Minted
        - OwnershipTransferred
        - Paused
        - RevokedOperator
        - Sent
        - StrategyAdded
        - StrategyRemoved
        - StrategyReturnedToQueue
        - StrategyRevoked
        - Transfer
        - Unpaused
        - ContractUpgraded
        - Withdraw
      abis:
        - name: Vault
          file: ../../abis/VaultImplementation.json
        - name: ERC20
          file: ../../abis/ERC20.json
        - name: ChainLinkPriceFeed
          file: ../../abis/ChainLinkPriceFeed.json
      eventHandlers:
        - event: AdminChanged(address,address)
          handler: handleAdminChanged
        - event: Approval(indexed address,indexed address,uint256)
          handler: handleApproval
        - event: AuthorizedOperator(indexed address,indexed address)
          handler: handleAuthorizedOperator
        - event: BeaconUpgraded(indexed address)
          handler: handleBeaconUpgraded
        - event: BorrowerDebtManagementReported(indexed
            address,uint256,uint256,uint256,uint256,uint256)
          handler: handleBorrowerDebtManagementReported
        - event: Burned(indexed address,indexed address,uint256,bytes,bytes)
          handler: handleBurned
        - event: Deposit(indexed address,indexed address,uint256,uint256)
          handler: handleDeposit
        - event: Initialized(uint8)
          handler: handleInitialized
        - event: LockedProfitReleaseRateChanged(uint256)
          handler: handleLockedProfitReleaseRateChanged
        - event: Minted(indexed address,indexed address,uint256,bytes,bytes)
          handler: handleMinted
        - event: OwnershipTransferred(indexed address,indexed address)
          handler: handleOwnershipTransferred
        - event: Paused(address)
          handler: handlePaused
        - event: RevokedOperator(indexed address,indexed address)
          handler: handleRevokedOperator
        - event: Sent(indexed address,indexed address,indexed address,uint256,bytes,bytes)
          handler: handleSent
        - event: StrategyAdded(indexed address,uint256)
          handler: handleStrategyAdded
        - event: StrategyRemoved(indexed address,bool)
          handler: handleStrategyRemoved
        - event: StrategyReturnedToQueue(indexed address)
          handler: handleStrategyReturnedToQueue
        - event: StrategyRevoked(indexed address)
          handler: handleStrategyRevoked
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Unpaused(address)
          handler: handleUnpaused
        - event: Upgraded(indexed address)
          handler: handleUpgraded
        - event: Withdraw(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleWithdraw
      file: ../../src/event-handlers.ts
  - kind: ethereum
    name: BTCB Vault
    network: sepolia
    source:
      address: "0x4D5Fc5F1125bDB0E4f33A1197AcD91c4B1F3d7eb"
      abi: Vault
      startBlock: 4808168
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Vault
        - ContractAdminChanged
        - Approval
        - AuthorizedOperator
        - ContractBeaconUpgraded
        - BorrowerDebtManagementReported
        - Burned
        - Deposit
        - Initialized
        - LockedProfitReleaseRateChanged
        - Minted
        - OwnershipTransferred
        - Paused
        - RevokedOperator
        - Sent
        - StrategyAdded
        - StrategyRemoved
        - StrategyReturnedToQueue
        - StrategyRevoked
        - Transfer
        - Unpaused
        - ContractUpgraded
        - Withdraw
      abis:
        - name: Vault
          file: ../../abis/VaultImplementation.json
        - name: ERC20
          file: ../../abis/ERC20.json
        - name: ChainLinkPriceFeed
          file: ../../abis/ChainLinkPriceFeed.json
      eventHandlers:
        - event: AdminChanged(address,address)
          handler: handleAdminChanged
        - event: Approval(indexed address,indexed address,uint256)
          handler: handleApproval
        - event: AuthorizedOperator(indexed address,indexed address)
          handler: handleAuthorizedOperator
        - event: BeaconUpgraded(indexed address)
          handler: handleBeaconUpgraded
        - event: BorrowerDebtManagementReported(indexed
            address,uint256,uint256,uint256,uint256,uint256)
          handler: handleBorrowerDebtManagementReported
        - event: Burned(indexed address,indexed address,uint256,bytes,bytes)
          handler: handleBurned
        - event: Deposit(indexed address,indexed address,uint256,uint256)
          handler: handleDeposit
        - event: Initialized(uint8)
          handler: handleInitialized
        - event: LockedProfitReleaseRateChanged(uint256)
          handler: handleLockedProfitReleaseRateChanged
        - event: Minted(indexed address,indexed address,uint256,bytes,bytes)
          handler: handleMinted
        - event: OwnershipTransferred(indexed address,indexed address)
          handler: handleOwnershipTransferred
        - event: Paused(address)
          handler: handlePaused
        - event: RevokedOperator(indexed address,indexed address)
          handler: handleRevokedOperator
        - event: Sent(indexed address,indexed address,indexed address,uint256,bytes,bytes)
          handler: handleSent
        - event: StrategyAdded(indexed address,uint256)
          handler: handleStrategyAdded
        - event: StrategyRemoved(indexed address,bool)
          handler: handleStrategyRemoved
        - event: StrategyReturnedToQueue(indexed address)
          handler: handleStrategyReturnedToQueue
        - event: StrategyRevoked(indexed address)
          handler: handleStrategyRevoked
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Unpaused(address)
          handler: handleUnpaused
        - event: Upgraded(indexed address)
          handler: handleUpgraded
        - event: Withdraw(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleWithdraw
      file: ../../src/event-handlers.ts
