[profile.default]
src = 'src'
out = 'out'
libs = ['../../node_modules', 'node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'

solc = '0.8.15'

# Some tests rely on a non-zero timestamp
block_timestamp = 200000

fuzz_runs = 100