[profile.default]
src = 'src'
out = 'out'
libs = ['../../node_modules', 'node_modules', 'lib']
test = 'test/unit'
cache_path  = 'forge-cache'

solc = '0.8.26'

# Some tests rely on a non-zero timestamp
block_timestamp = 200000

[fuzz]
max_test_rejects = 131072 # default value too low for part of the tests
