[profile.default]
src = 'src'
out = 'out'
libs = ['../../node_modules', 'node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'

solc = '0.8.15'

eth-rpc-url = 'http://localhost:8545'

fuzz_runs = 100