[default]
src = 'src'
out = 'out'
libs = ['../../node_modules', 'node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'

solc = '0.8.15'

eth-rpc-url = 'https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161'
block_number = 14668845 # Apr - 27 - 2021

fuzz_runs = 100