name: Check dApp API compatibility

on:
  push:
    branches:
      - main
    paths:
      - "packages/web/schema.graphql"
  
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
    paths:
      - "packages/web/schema.graphql"

jobs:
  check:
    name: Check GraphQL schema compatibility
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --ignore-scripts

      - name: Generate types
        run: |-
          cd packages/web
          yarn gen:gql-types

      - name: Build dApp
        run: |-
          cd packages/web
          yarn build

