name: Check Gas usage

on:
  # Dont check in master branch to avoid conflict commits
  
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
    paths:
      - "packages/contracts/**"

jobs:
  gas-usage:
    name: Check Gas usage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          # fix for EndBug/add-and-commit
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --ignore-scripts

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-e15e33a07c0920189fc336391f538c3dad53da73 # https://github.com/foundry-rs/foundry/releases/tag/nightly-e15e33a07c0920189fc336391f538c3dad53da73

      - name: Report gas usage in tests
        run: |-
          cd packages/contracts
          forge snapshot

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with: 
          default_author: github_actions
          message: 'Save gas usage snapshot'
          fetch: --no-tags --recurse-submodules=no # Prevent failure due to submodules
