name: Deploy Protocol to Testnet Preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
    paths:
      - "packages/contracts/**"

jobs:
  deploy: 
    name: Deploy Protocol
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --ignore-scripts

      # TODO: Switch to Github environments
      - name: Set deploy enviroment to Sepolia
        run: echo "HARDHAT_NETWORK=sepolia" >> $GITHUB_ENV

      - name: Deploy Protocol
        run: |-
          cd packages/contracts
          yarn hardhat deploy

      # Allow etherscan to index the contracts and prevent failures
      - name: Wait for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Publish code on Etherscan
        run: |-
          cd packages/contracts
          yarn hardhat etherscan-verify --license AGPL-3.0 --force-license --solc-input
      
      # Working not on all blockchains, BSC for example
      - name: Publish code on Sourcify
        run: |-
          cd packages/contracts
          yarn hardhat sourcify

      # Usefull for automated scripts
      - name: Export deployments to JSON config
        run: |-
          cd packages/contracts
          yarn hardhat export --export-all './deployments/deployed.json'

      # Prefered to import in TypeScript
      - name: Export deployments to TypeScript config
        run: |-
          cd packages/contracts
          yarn hardhat export --export-all './deployments/deployed.ts'

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with: 
          default_author: github_actions
          message: 'Deployed contracts to Sepolia'
  