name: Deploy Subgraph to Mainnet

on:
  push:
    branches:
      - staging
      - development
    paths:
      - "packages/subgraph/**"

jobs:
  deploy: 
    name: Deploy Subgraph
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          # fix for EndBug/add-and-commit
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Read version from package.json and set version variables
        run: |
          VER=$(grep version packages/subgraph/package.json | cut -d ':' -f 2 | cut -d '"' -f 2)
          echo "VERSION=$VER" >> $GITHUB_ENV
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --ignore-scripts
      
      - name: Build subgraph
        run: |-
          cd packages/subgraph
          yarn build

      - name: Deploy subgraph
        env:
          VERSION: ${{ env.VERSION }}
          SUBGRAPH_DEPLOY_KEY: ${{ secrets.SUBGRAPH_DEPLOY_KEY }}
          SUBGRAPH_ENVIRONMENT: ${{ vars.SUBGRAPH_ENVIRONMENT }} # eonian-sepolia-testnet
        # Use warapper for yarn deploy command to highlight step failure
        run: |-
          cd packages/subgraph
          ./deploy.sh
  
  