name: Generate Subgraphs

on:
  pull_request:
    branches:
      - development
    types:
      - opened
      - labeled
    paths:
      - "packages/subgraph/**"

jobs:
  generate: 
    name: Generate Subgraphs
    runs-on: ubuntu-latest
    environment: preview
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          # fix for EndBug/add-and-commit
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Resolve bump label
        id: bump
        uses: zwaldowski/match-label-action@v1
        with:
          allowed: major,minor,patch   

      - name: Read version from package.json and set version variables
        run: |
          VER=$(grep version packages/subgraph/package.json | cut -d ':' -f 2 | cut -d '"' -f 2)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Generate new version
        id: next_version
        uses: leovs09/semver-release-action@v3
        with:
          version: ${{ env.VERSION }}
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save new version in package.json
        run: |-
          cd packages/subgraph
          sed -i -E 's/"version": "(.*)",/"version": "${{ steps.next_version.outputs.version }}",/g' package.json

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --ignore-scripts
      
      - name: Generate subgraph environments configurations
        run: |-
          cd packages/subgraph
          yarn gen:configs

      # TODO: add step that load contracts ABIs before generating schema

      - name: Generate subgraph schema code
        run: |-
          cd packages/subgraph
          yarn gen:code

      - name: Build subgraph
        run: |-
          cd packages/subgraph
          yarn build

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with: 
          default_author: github_actions
          message: '[skip ci] Generate subgraph configs and schema'
          fetch: --no-tags --recurse-submodules=no # Prevent failure due to submodules
          pull: '--rebase --autostash'