name: Verify Contracts PR

on:
  push:
    paths:
      - "packages/contracts/**"

jobs:
  test:
    name: Test contracts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --ignore-scripts

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: |-
          cd packages/contracts
          FOUNDRY_FUZZ_RUNS=1000 forge test -vvv