name: Upload source maps to LogRocket

on:
  push:
    branches:
      - main
      - staging
      - development
    paths:
      - "packages/web/**"
  pull_request:
    types:
      - labeled
    paths:
      - "packages/web/**"

jobs:
  upload:
    # If it's a pull request, then only execute the job when a certain label is present
    if: github.event.label.name == 'release_logrocket' || github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --ignore-scripts

      - name: Build
        env:
          BUILD_SOURCE_MAPS: true
        run: |-
          cd packages/web
          yarn build

      - name: Install LogRocket CLI
        run: yarn global add logrocket-cli

      - name: Create LogRocket release
        run: logrocket release ${{ github.sha }} --apikey="${{ secrets.LOGROCKET_API_KEY }}"

      - name: Upload source maps
        run: logrocket upload packages/web/.next/static/chunks ${{ github.sha }} --apikey="${{ secrets.LOGROCKET_API_KEY }}" --url-prefix="~/_next/static/chunks/"

