name: Verify dApp

on:
  push:
    branches:
      - main
      - staging
      - development
  
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  # Add linting job after migration to nextjs version with given fix https://github.com/vercel/next.js/issues/44424
  
  test:
    name: Test dApp
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --ignore-scripts

      - name: Run tests
        run: |-
          cd packages/web
          yarn test:ci


