name: Verify Subgraph

on:
  push:
    branches:
      - main
      - staging
      - development
  
  pull_request:
    branches:
      - main
      - staging
      - development
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Test subgraph
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Copy local schema
        run: |-
          cd packages/subgraph
          npm run copy:local-schema

      - name: Generate code
        run: |-
          cd packages/subgraph
          npm run gen:code

      - name: Run tests 
        run: |-
          cd packages/subgraph
          npm run test:only



